// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (discord_id)
VALUES ($1)
RETURNING id, discord_id, last_updated
`

func (q *Queries) CreateGuild(ctx context.Context, discordID pgtype.Text) (Guild, error) {
	row := q.db.QueryRow(ctx, createGuild, discordID)
	var i Guild
	err := row.Scan(&i.ID, &i.DiscordID, &i.LastUpdated)
	return i, err
}

const getGuildByDiscordId = `-- name: GetGuildByDiscordId :one
SELECT id, discord_id, last_updated FROM guilds
WHERE discord_id = $1
`

func (q *Queries) GetGuildByDiscordId(ctx context.Context, discordID pgtype.Text) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuildByDiscordId, discordID)
	var i Guild
	err := row.Scan(&i.ID, &i.DiscordID, &i.LastUpdated)
	return i, err
}

const getGuildById = `-- name: GetGuildById :one
SELECT id, discord_id, last_updated FROM guilds
WHERE id = $1
`

func (q *Queries) GetGuildById(ctx context.Context, id int64) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuildById, id)
	var i Guild
	err := row.Scan(&i.ID, &i.DiscordID, &i.LastUpdated)
	return i, err
}

const updateLastRanTime = `-- name: UpdateLastRanTime :one
UPDATE guilds
SET last_updated = now()
WHERE discord_id = $1
RETURNING id, discord_id, last_updated
`

func (q *Queries) UpdateLastRanTime(ctx context.Context, discordID pgtype.Text) (Guild, error) {
	row := q.db.QueryRow(ctx, updateLastRanTime, discordID)
	var i Guild
	err := row.Scan(&i.ID, &i.DiscordID, &i.LastUpdated)
	return i, err
}
