// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Summoner struct {
	ID         int64
	Name       pgtype.Text
	Tagline    pgtype.Text
	Playeruuid pgtype.Text
}
