// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Guild struct {
	ID          int64
	DiscordID   pgtype.Text
	LastUpdated pgtype.Timestamptz
}

type Summoner struct {
	ID         int64
	Name       pgtype.Text
	TagLine    pgtype.Text
	PlayerUuid pgtype.Text
}
