// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateGuild(ctx context.Context, discordID pgtype.Text) (GuildRow, error)
	CreateSummoner(ctx context.Context, arg CreateSummonerParams) (SummonerRow, error)
	GetGuildByDiscordId(ctx context.Context, discordID pgtype.Text) (GuildRow, error)
	GetGuildById(ctx context.Context, id int64) (GuildRow, error)
	GetSummoner(ctx context.Context, id int64) (SummonerRow, error)
	GetSummonerByNameAndTag(ctx context.Context, arg GetSummonerByNameAndTagParams) (SummonerRow, error)
	UpdateLastRanTime(ctx context.Context, discordID pgtype.Text) (GuildRow, error)
	UpdateSummoner(ctx context.Context, arg UpdateSummonerParams) (UpdateSummonerRow, error)
}

var _ Querier = (*Queries)(nil)
