// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summoners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSummoner = `-- name: CreateSummoner :one
INSERT INTO summoners (name, tag_line, player_uuid)
VALUES ($1, $2, $3)
RETURNING id, name, tag_line, player_uuid
`

type CreateSummonerParams struct {
	Name       pgtype.Text
	TagLine    pgtype.Text
	PlayerUuid pgtype.Text
}

func (q *Queries) CreateSummoner(ctx context.Context, arg CreateSummonerParams) (Summoner, error) {
	row := q.db.QueryRow(ctx, createSummoner, arg.Name, arg.TagLine, arg.PlayerUuid)
	var i Summoner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagLine,
		&i.PlayerUuid,
	)
	return i, err
}

const getSummoner = `-- name: GetSummoner :one
SELECT id, name, tag_line, player_uuid FROM summoners
WHERE id = $1
`

func (q *Queries) GetSummoner(ctx context.Context, id int64) (Summoner, error) {
	row := q.db.QueryRow(ctx, getSummoner, id)
	var i Summoner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagLine,
		&i.PlayerUuid,
	)
	return i, err
}

const getSummonerByNameAndTag = `-- name: GetSummonerByNameAndTag :one
SELECT id, name, tag_line, player_uuid FROM summoners
WHERE name = $1 AND tag_line = $2
`

type GetSummonerByNameAndTagParams struct {
	Name    pgtype.Text
	TagLine pgtype.Text
}

func (q *Queries) GetSummonerByNameAndTag(ctx context.Context, arg GetSummonerByNameAndTagParams) (Summoner, error) {
	row := q.db.QueryRow(ctx, getSummonerByNameAndTag, arg.Name, arg.TagLine)
	var i Summoner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagLine,
		&i.PlayerUuid,
	)
	return i, err
}
