// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summoners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSummoner = `-- name: CreateSummoner :one
INSERT INTO summoners (name, tagline, playerUuid)
VALUES ($1, $2, $3)
RETURNING id, name, tagline, playeruuid
`

type CreateSummonerParams struct {
	Name       pgtype.Text
	Tagline    pgtype.Text
	Playeruuid pgtype.Text
}

func (q *Queries) CreateSummoner(ctx context.Context, arg CreateSummonerParams) (Summoner, error) {
	row := q.db.QueryRow(ctx, createSummoner, arg.Name, arg.Tagline, arg.Playeruuid)
	var i Summoner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tagline,
		&i.Playeruuid,
	)
	return i, err
}

const getSummoner = `-- name: GetSummoner :one
SELECT id, name, tagline, playeruuid FROM summoners
WHERE id = $1
`

func (q *Queries) GetSummoner(ctx context.Context, id int64) (Summoner, error) {
	row := q.db.QueryRow(ctx, getSummoner, id)
	var i Summoner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tagline,
		&i.Playeruuid,
	)
	return i, err
}

const getSummonerByNameAndTag = `-- name: GetSummonerByNameAndTag :one
SELECT id, name, tagline, playeruuid FROM summoners
WHERE name = $1 AND tagline = $2
`

type GetSummonerByNameAndTagParams struct {
	Name    pgtype.Text
	Tagline pgtype.Text
}

func (q *Queries) GetSummonerByNameAndTag(ctx context.Context, arg GetSummonerByNameAndTagParams) (Summoner, error) {
	row := q.db.QueryRow(ctx, getSummonerByNameAndTag, arg.Name, arg.Tagline)
	var i Summoner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tagline,
		&i.Playeruuid,
	)
	return i, err
}
