// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summoners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSummoner = `-- name: CreateSummoner :one
INSERT INTO summoners (name, tag_line, player_uuid)
VALUES ($1, $2, $3)
RETURNING id, name, tag_line, player_uuid
`

type CreateSummonerParams struct {
	Name       pgtype.Text
	TagLine    pgtype.Text
	PlayerUuid pgtype.Text
}

func (q *Queries) CreateSummoner(ctx context.Context, arg CreateSummonerParams) (SummonerRow, error) {
	row := q.db.QueryRow(ctx, createSummoner, arg.Name, arg.TagLine, arg.PlayerUuid)
	var i SummonerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagLine,
		&i.PlayerUuid,
	)
	return i, err
}

const getSummoner = `-- name: GetSummoner :one
SELECT id, name, tag_line, player_uuid FROM summoners
WHERE id = $1
`

func (q *Queries) GetSummoner(ctx context.Context, id int64) (SummonerRow, error) {
	row := q.db.QueryRow(ctx, getSummoner, id)
	var i SummonerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagLine,
		&i.PlayerUuid,
	)
	return i, err
}

const getSummonerByNameAndTag = `-- name: GetSummonerByNameAndTag :one
SELECT id, name, tag_line, player_uuid FROM summoners
WHERE name = $1 AND tag_line = $2
`

type GetSummonerByNameAndTagParams struct {
	Name    pgtype.Text
	TagLine pgtype.Text
}

func (q *Queries) GetSummonerByNameAndTag(ctx context.Context, arg GetSummonerByNameAndTagParams) (SummonerRow, error) {
	row := q.db.QueryRow(ctx, getSummonerByNameAndTag, arg.Name, arg.TagLine)
	var i SummonerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagLine,
		&i.PlayerUuid,
	)
	return i, err
}

const updateSummoner = `-- name: UpdateSummoner :one
WITH summoner_upsert AS (
  INSERT INTO summoners (name, tag_line, player_uuid)
  VALUES ($1, $2, $3)
  ON CONFLICT (player_uuid)
  DO UPDATE SET
    name = EXCLUDED.name,
    tag_line = EXCLUDED.tag_line
  RETURNING id
),
summoner_id AS (
  SELECT id FROM summoner_upsert
  UNION
  SELECT id FROM summoners WHERE player_uuid = $3
),
guild_upsert AS (
  INSERT INTO guilds (discord_id, last_updated)
  VALUES ($4, now())
  ON CONFLICT (discord_id)
  DO UPDATE SET
    last_updated = EXCLUDED.last_updated
  RETURNING id
),
guild_id AS (
  SELECT id FROM guild_upsert
  UNION
  SELECT id FROM guilds WHERE discord_id = $4
),
inserted AS (
  INSERT INTO guild_summoners (
    summoner_id,
    guild_id,
    flex_games_played,
    flex_tier,
    flex_rank,
    flex_wins,
    flex_lp,
    solo_duo_games_played,
    solo_duo_tier,
    solo_duo_rank,
    solo_duo_wins,
    solo_duo_lp,
    last_updated
  )
  VALUES (
    (SELECT id FROM summoner_id),
    (SELECT id FROM guild_id),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    NOW()
  )
  RETURNING id, summoner_id, guild_id, flex_games_played, flex_tier, flex_rank, flex_wins, flex_lp, solo_duo_games_played, solo_duo_tier, solo_duo_rank, solo_duo_wins, solo_duo_lp, last_updated
)
SELECT inserted.id, summoner_id, guild_id, flex_games_played, flex_tier, flex_rank, flex_wins, flex_lp, solo_duo_games_played, solo_duo_tier, solo_duo_rank, solo_duo_wins, solo_duo_lp, last_updated, summoners.id, name, tag_line, player_uuid FROM inserted
JOIN summoners ON summoners.id = inserted.summoner_id
`

type UpdateSummonerParams struct {
	Name               pgtype.Text
	TagLine            pgtype.Text
	PlayerUuid         pgtype.Text
	DiscordID          pgtype.Text
	FlexGamesPlayed    pgtype.Int4
	FlexTier           pgtype.Text
	FlexRank           pgtype.Text
	FlexWins           pgtype.Int4
	FlexLp             pgtype.Int4
	SoloDuoGamesPlayed pgtype.Int4
	SoloDuoTier        pgtype.Text
	SoloDuoRank        pgtype.Text
	SoloDuoWins        pgtype.Int4
	SoloDuoLp          pgtype.Int4
}

type UpdateSummonerRow struct {
	ID                 int64
	SummonerID         pgtype.Int8
	GuildID            pgtype.Int8
	FlexGamesPlayed    pgtype.Int4
	FlexTier           pgtype.Text
	FlexRank           pgtype.Text
	FlexWins           pgtype.Int4
	FlexLp             pgtype.Int4
	SoloDuoGamesPlayed pgtype.Int4
	SoloDuoTier        pgtype.Text
	SoloDuoRank        pgtype.Text
	SoloDuoWins        pgtype.Int4
	SoloDuoLp          pgtype.Int4
	LastUpdated        pgtype.Timestamptz
	ID_2               int64
	Name               pgtype.Text
	TagLine            pgtype.Text
	PlayerUuid         pgtype.Text
}

func (q *Queries) UpdateSummoner(ctx context.Context, arg UpdateSummonerParams) (UpdateSummonerRow, error) {
	row := q.db.QueryRow(ctx, updateSummoner,
		arg.Name,
		arg.TagLine,
		arg.PlayerUuid,
		arg.DiscordID,
		arg.FlexGamesPlayed,
		arg.FlexTier,
		arg.FlexRank,
		arg.FlexWins,
		arg.FlexLp,
		arg.SoloDuoGamesPlayed,
		arg.SoloDuoTier,
		arg.SoloDuoRank,
		arg.SoloDuoWins,
		arg.SoloDuoLp,
	)
	var i UpdateSummonerRow
	err := row.Scan(
		&i.ID,
		&i.SummonerID,
		&i.GuildID,
		&i.FlexGamesPlayed,
		&i.FlexTier,
		&i.FlexRank,
		&i.FlexWins,
		&i.FlexLp,
		&i.SoloDuoGamesPlayed,
		&i.SoloDuoTier,
		&i.SoloDuoRank,
		&i.SoloDuoWins,
		&i.SoloDuoLp,
		&i.LastUpdated,
		&i.ID_2,
		&i.Name,
		&i.TagLine,
		&i.PlayerUuid,
	)
	return i, err
}
